name: Build WebGL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: Library
        key: Library-${{ hashFiles('**/*.cs') }}

    - uses: game-ci/unity-builder@v3
      with:
        targetPlatform: WebGL
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    - uses: actions/upload-artifact@v4
      with:
        name: JamJam-WebGL
        path: build/WebGL

